<?php
/**
 * Basic test class.
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    PHP_ArrayOf
 * @subpackage Tests
 * @author     Philippe Jausions <Philippe.Jausions@11abacus.com>
 * @copyight   2008 by Philippe Jausions / 11abacus
 * @license    http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @version    CVS: $Id$
 * @link       http://pear.php.net/package/PHP_ArrayOf
 */

/**
 * Required package to test
 */
require_once 'PHP/ArrayOf.php';

/**
 * Basic test class.
 *
 * This class accepts anything
 *
 * @category   PHP
 * @package    PHP_ArrayOf
 * @subpackage Tests
 * @author     Philippe Jausions <Philippe.Jausions@11abacus.com>
 * @copyight   2008 by Philippe Jausions / 11abacus
 * @license    http://www.opensource.org/licenses/bsd-license.php New BSD License
 * @link       http://pear.php.net/package/PHP_ArrayOf
 */
class PHP_ArrayOf_Anything extends PHP_ArrayOf
{
}

?>
